routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//---------------------------------------------------------
Route::get('contacto',function(){

	return View::make('contacto.index');
});
Route::get('tienda',function(){

	return View::make('tiendas.index');
});
Route::get('nosotros',function(){

	return View::make('nosotros.index');
});

Route::resource('tiendas','Web\Tienda\TiendaController');
Route::resource('tiendas.productos','Web\Tienda\TiendaProductoController');
Route::resource('tiendas.productos.fotos','Web\Tienda\TiendaProductoFotoController',['only'=>['index','destroy']]);
Route::resource('handbooks','Web\Handbook\HandbookController');

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    //
    protected $table="producto";

    protected $fillable=[
    	'id',
    	'nombre',
    	'descripcion',
    	'producto_id',
    	'producto_type',
    	'cantidad',
    	'precio'

    ];

    protected $hidden=[
    	'created_at',
    	'updated_at',
    ];

    public function producto(){
    	return $this->morphTo();
    }

    public function fotos(){
    	return $this->hasMany('App\FotoProducto', 'producto_id','id');
    }
}

app/Http/Controllers/Api/Producto/ProductoController.php
<?php

namespace App\Http\Controllers\Api\Producto;

use App\Producto;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $productos = Producto::orderBy('nombre','asc')->get();
        foreach ($productos as $producto) {
            $producto->producto;
            $producto->fotos;
        }
        return response()->json(['productos'=>$productos],200);
    }

}

resources/views/tiendas/producto/fotos/index.blade.php
@extends('layouts.app')
@section('content')
	{{-- expr --}}
	<div class="container-fluid" align="center">
		<main class="py-4">
			<div class="container card">
				<div class="row justify-content-center">
					<div class="container">
						<div class="col"><h1>Fotos de {{$producto->nombre}}</h1></div>
					</div>
				</div>
				<div class="container">
					<div class="row">
						@foreach ($fotos as $foto)
							{{-- expr --}}
							<div class="col-6" style="padding-bottom: 15px;padding-top: 15px;">
								<div class="card">
									<img src="{{ url('storage/') }}/{{$foto->image_path}}" style="height: 250px; width: 250px;">
									<form method="POST" action="{{ route('tiendas.productos.fotos.destroy',['tienda'=>$tienda,'producto'=>$producto,'foto'=>$foto]) }}">
										@csrf

										<input type="hidden" name="_method" value="DELETE">
										<button type="submit" class="btn btn-danger" onclick="return confirm('¿Estás seguro que desea eliminar esta foto?');">Eliminar</button>
									</form>
								</div>
							</div>
						@endforeach
						
					</div>
				</div>
			</div>
		</main>
	</div>
@endsection