routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//---------------------------------------------------------
Route::get('contacto',function(){

	return View::make('contacto.index');
});
Route::get('tienda',function(){

	return View::make('tiendas.index');
});
Route::get('nosotros',function(){

	return View::make('nosotros.index');
});

Route::resource('tiendas','Web\Tienda\TiendaController');
Route::resource('tiendas.productos','Web\Tienda\TiendaProductoController');
Route::resource('tiendas.productos.fotos','Web\Tienda\TiendaProductoFotoController',['only'=>['index','destroy']]);
Route::resource('handbooks','Web\Handbook\HandbookController');

app/Handbook.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Handbook extends Model
{
    //
    protected $table="handbooks";

    protected $fillable=[
    	'id',
    	'nombre',
    	'descripcion',
    	'path'
    ];

    protected $hidden =[
    	'created_at',
    	'updated_at'
    ];
}

app/Http/Controllers/Api/Handbook/HandbookController.php
<?php

namespace App\Http\Controllers\Api\Handbook;


use App\Handbook;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class HandbookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $handbooks = Handbook::get();
        return response()->json(['handbooks'=>$handbooks],201);
    }


     /**
     * Download the file request.
     *
     * @return \Illuminate\Http\Response
     */

     public function download($path)
     {
        // dd($path);
        $file = Handbook::where('path',$path)->firstOrFail();
       
        // dd($nombre);
        if ($file->nombre){
             $nombre = Str::ascii($file->nombre);
            $nombre = str_slug($nombre,'_');
            return Storage::download('public/handbook/'.$path,$nombre.'.pdf');
        }
        else{
            return response()->json(['message'=>'Archivo no encontrado'],404);
        }
     }
}

app/Http/Controllers/Web/Handbook/HandbookController.php
<?php

namespace App\Http\Controllers\Web\Handbook;

use App\Handbook;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;


class HandbookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $handbooks = Handbook::orderBy('nombre','asc')->get();

        return view('handbook.index',['handbooks'=>$handbooks]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $edit = false;
        return view('handbook.form',['edit'=>$edit]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd($request->all());
            // dd($_SERVER['CONTENT_LENGTH']);
        set_time_limit(0);
        ini_set('memory_limit','256M');
        ini_set('upload_max_filesize','256M');
        ini_set('post_max_size','256M');
        $rules = [
            'nombre'=>'required',
            'handbook'=> 'required|file|mimes:pdf',
        ];
        $this->validate($request,$rules);
        if ($request->file('handbook')->isValid()) {

            $file=$request->handbook;
            $path_name = str_random(10).'.pdf';
            $file->storeAs('public/handbook',$path_name);
            Handbook::create([
                'nombre'=>$request->nombre,
                'descripcion'=>$request->descripcion,
                'path'=>$path_name
            ]);
        }
        return redirect()->route('handbooks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Handbook  $handbook
     * @return \Illuminate\Http\Response
     */
    public function show(Handbook $handbook)
    {
        //
        return view('handbook.show',['handbook'=>$handbook]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Handbook  $handbook
     * @return \Illuminate\Http\Response
     */
    public function edit(Handbook $handbook)
    {
        //
        $edit = true;
        return view('handbook.form',['edit'=>$edit,'handbook'=>$handbook]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Handbook  $handbook
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Handbook $handbook)
    {
        //
        // $request->all();
        $rules = [
            'nombre'=>'required',
        ];
        $this->validate($request,$rules);
        $handbook->update([
            'nombre'=>$request->nombre,
            'descripcion'=>$request->descripcion,
        ]);
        return redirect()->route('handbooks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Handbook  $handbook
     * @return \Illuminate\Http\Response
     */
    public function destroy(Handbook $handbook)
    {
        //
        $delete = Storage::delete('/public/handbook/'.$handbook->path);
        if ($delete) {
            $handbook->delete();
        }
        return redirect()->route('handbooks.index');
        
    }
}

resources/views/handbook/form.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">
						Handbook
					</div>
					<div class="card-body">
						<form method="POST" action="{{ $edit == false ? route('handbooks.store') : route('handbooks.update',$handbook) }}" @if ($edit == false)
							{{-- expr --}}
							enctype='multipart/form-data'
						@endif>
							@csrf

							@if ($edit == true)
								{{-- expr --}}
								<input type="hidden" name="_method" value="PUT">
							@endif

							<div class="form-group row">
								<label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre del manual:</label>
								<div class="col-md-6">
									<input id="nombre" type="text" class="form-control {{ $errors->has('nombre') ? ' is-invalid' : ''  }}" name="nombre" value="{{ $edit ? $handbook->nombre : old('nombre') }}" required autofocus="">
									@if ($errors->has('nombre'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("nombre")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">
								<label for="descripcion" class="col-md-4 col-form-label text-md-right">Descripción:</label>
								<div class="col-md-6">
									<textarea id="descripcion" type="text" class="form-control {{ $errors->has('descripcion') ? ' is-invalid' : ''  }}" name="descripcion">{{ $edit ? $handbook->descripcion : old('descripcion') }}</textarea>
									@if ($errors->has('descripcion'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("descripcion")}}</strong>
										</span>
									@endif
								</div>
							</div>
							@if ($edit)
								{{-- true expr --}}
								<div class="form-group row">
									<iframe src="{{ url('storage/handbook/'.$handbook->path) }}" style="width: 100%; height: 300px;"></iframe>
								</div>
							@else
								{{-- false expr --}}
							<div class="form-group row">
								<label for="handbook" class="col-md-4 col-form-label text-md-right">Manual:</label>
								<div class="col-md-6">
									<input type="file" id="handbook" name="handbook" accept="application/pdf" class="form-control {{ $errors->has('handbook') ? ' is-invalid' : ''  }}">
									@if ($errors->has('handbook'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("handbook")}}</strong>
										</span>
									@endif
								</div>
							</div>


							@endif
							
							
							

						<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Guardar handbook
                                </button>
                            </div>
                        </div>
						</form>

						
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/handbook/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid" align="center">
	<main class="py-4" id="app">
       <div class="container">
		  	<div class="row justify-content-center">
				<div class="container-fluid card">
					<div class="container">
						<div class="col">
							<h1>Handbooks</h1>
						</div>
						<div class="col-3 input-group input-group-lg mb-3">
					  		<a href="{{ route('handbooks.create') }}" class="btn btn-primary">Agregar Nuevo Manual</a>
						</div>
					</div>
					<table class="table">
						<thead class="thead-dark">
							<tr>
								<th scope="col">Nombre</th>
								<th scope="col">Descripción</th>
								<th scope="col">Fecha de creación</th>
								<th scope="col">Acción</th>
							</tr>
						</thead>
						<tbody>
							@forelse ($handbooks as $handbook)
								{{-- expr --}}
								<tr>
									<th scope="row">{{$handbook->nombre}}</th>
									<th>{{$handbook->descripcion}}</th>
									<th>{{$handbook->created_at->format('Y-m-d')}}</th>
									<th>
										<a href="{{ route('handbooks.edit',['handbook'=>$handbook]) }}" class="btn btn-link">Editar</a>
										<form method="POST" action="{{ route('handbooks.destroy',['handbook'=>$handbook]) }}" style="display: inline-block;">
											@csrf
											<input type="hidden" name="_method" value="DELETE">
											<button type="submit" class="btn btn-link" onclick="return confirm('¿Estás seguro que desea eliminar este manual?');">Eliminar</button>
										</form>
									</th>
								</tr>
							@empty
								{{-- empty expr --}}
								<div class="alert alert-danger" role="alert">
									<span>No hay manuales</span>
								</div>
							@endforelse
						</tbody>
					</table>
				</div>
			</div>
		</div>
    </main>
</div>
@endsection