routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//---------------------------------------------------------
Route::get('contacto',function(){

	return View::make('contacto.index');
});
Route::get('tienda',function(){

	return View::make('tiendas.index');
});
Route::get('nosotros',function(){

	return View::make('nosotros.index');
});

Route::resource('tiendas','Web\Tienda\TiendaController');
Route::resource('tiendas.productos','Web\Tienda\TiendaProductoController');
Route::resource('tiendas.productos.fotos','Web\Tienda\TiendaProductoFotoController',['only'=>['index','destroy']]);
Route::resource('handbooks','Web\Handbook\HandbookController');

app/Tienda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tienda extends Model
{
    //

    protected $table="tienda";

    protected $fillable=[
    	'id',
    	'nombre',
    	'descripcion',
    	'nombre_contacto',
    	'puesto_contacto',
    	'correo_contacto',
    	'telefono_contacto',
    	'telefono',
    	'long',
    	'lat',
    	'locacion'
    ];

    protected $hidden=[
    	'created_at',
    	'updated_at',
    ];

    public function productos(){
    	return $this->morphMany('App\Producto','producto');
    }

    public function getMapLink(){
        return 'https://www.google.com.mx/maps?q=' . $this->lat . ',' . $this->long;
    }


}

app/Http/Controllers/Web/Tienda/TiendaController.php
<?php

namespace App\Http\Controllers\Web\Tienda;

use App\Tienda;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class TiendaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $tiendas = Tienda::paginate(5);
        return view('tiendas.index',['tiendas'=>$tiendas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $edit = false;
        return view('tiendas.form',['edit'=>$edit]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
         $rules = [
            'nombre'=> 'required',
            'nombre_contacto'=>'required',
            'puesto_contacto'=>'required',
            'correo_contacto'=>'required',
            'telefono_contacto'=>'required',
            'locacion'=> 'required',
            'telefono'=> 'required'
        ];
        $this->validate($request,$rules);
        $tienda = Tienda::create($request->all());

        return redirect()->route('tiendas.productos.create',['tienda'=>$tienda]);


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function show(Tienda $tienda)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function edit(Tienda $tienda)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tienda $tienda)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tienda $tienda)
    {
        //
        foreach ($tienda->productos as $producto) {
            foreach ($producto->fotos as $foto) {
                $delete =Storage::delete('/public/'.$foto->image_path);
                if ($delete) {
                    $foto->delete();
                }
            }
            $producto->delete();
        }
        $tienda->delete();
        return redirect()->route('tiendas.index');
    }
}

app/Http/Controllers/Web/Tienda/TiendaProductoController.php
<?php

namespace App\Http\Controllers\Web\Tienda;

use App\Http\Controllers\Controller;
use App\Producto;
use App\Tienda;
use App\FotoProducto;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;

class TiendaProductoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Tienda $tienda)
    {
        //
        $productos = $tienda->productos()->get();
        return view('tiendas.producto.index',['tienda'=>$tienda,'productos'=>$productos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Tienda $tienda)
    {
        //
        $edit = false;
        return view('tiendas.producto.form',['tienda'=>$tienda,'edit'=>$edit]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Tienda $tienda,Request $request)
    {
        //
        // dd($request->all());
        // dd($imagenes);
        $inputs = $request->all();
        $rules = [
            'nombre'=>'required',
            'cantidad' => 'required|numeric',
            'precio' => 'required|numeric',
            'imagen[]'=> 'image|mimes:jpg,jpeg,png',
        ];
        $imagenes = $request->imagen;
        $this->validate($request,$rules);
        $producto = Producto::create([
            "nombre" => $inputs['nombre'],
            'descripcion' => $inputs['descripcion'],
            'producto_id' => $inputs['tienda_id'],  
            'producto_type' => "App\Tienda",
            'cantidad' => $inputs['cantidad'],
            'precio' => $inputs['precio']
        ]);
        foreach ($imagenes as $imagen) {
            $path_image = $imagen->storeAs('productos/'.$producto->id,str_random(10).'.jpg','public');
            FotoProducto::create([
                'producto_id'=>$producto->id,
                'image_path'=>$path_image,
            ]);
        }


        return redirect()->route('tiendas.productos.index',['tienda'=>$tienda]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function show(Tienda $tienda,Producto $producto)
    {
        //
        // return view('tiendas.producto.show',['producto'=>$producto,'tienda'=>$tienda]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function edit(Tienda $tienda,Producto $producto)
    {
        //
        $edit = true;
        return view('tiendas.producto.form',['tienda'=>$tienda,'producto'=>$producto, 'edit'=>$edit]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tienda $tienda,Producto $producto)
    {
        //
        $inputs = $request->all();
        $rules = [
            'nombre'=>'required',
            'cantidad' => 'required|numeric',
            'precio' => 'required|numeric',
        ];
        $this->validate($request,$rules);
        $producto->update([
            "nombre" => $inputs['nombre'],
            'descripcion' => $inputs['descripcion'],
            'cantidad' => $inputs['cantidad'],
            'precio' => $inputs['precio']
        ]);
        if ($request->imagen) {
            $imagenes = $request->imagen;
            foreach ($imagenes as $imagen) {
            $path_image = $imagen->storeAs('productos/'.$producto->id,str_random(10).'.jpg','public');
            FotoProducto::create([
                'producto_id'=>$producto->id,
                'image_path'=>$path_image,
            ]);
        }
        }
        return redirect()->route('tiendas.productos.index',['tienda'=>$tienda]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tienda $tienda, Producto $producto)
    {
        //
        // dd($producto);
        if($producto->producto_id == $tienda->id && $producto->producto_type == 'App\Tienda'){
            foreach ($producto->fotos as $foto) {
                $delete =Storage::delete('/public/'.$foto->image_path);
                if ($delete) {
                    $foto->delete();
                }
            }
            $producto->delete();
        }
        return redirect()->route('tiendas.productos.index',['tienda'=>$tienda]);
    }
}

app/Http/Controllers/Web/Tienda/TiendaProductoFotoController.php
<?php

namespace App\Http\Controllers\Web\Tienda;

use App\FotoProducto;
use App\Producto;
use App\Tienda;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TiendaProductoFotoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Tienda $tienda,Producto $producto)
    {
        //
        $fotos = $producto->fotos;
        return view('tiendas.producto.fotos.index',['tienda'=>$tienda,'producto'=>$producto,'fotos'=>$fotos]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\FotoProducto  $fotoProducto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tienda $tienda,Producto $producto,FotoProducto $foto)
    {
        //
        if($producto->id == $foto->producto_id){
            $delete =Storage::delete('/public/'.$foto->image_path);
            if ($delete) {
                $foto->delete();
                
            }
            
        }

        return redirect()->route('tiendas.productos.fotos.index',['tienda'=>$tienda,'producto'=>$producto]);


    }
}

resources/views/tiendas/form.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">
						Tienda
					</div>
					<div class="card-body">
						<form method="POST" action="{{ $edit == false ? route('tiendas.store') : route('tiendas.update',$tienda) }}">
							@csrf

							@if ($edit == true)
								{{-- expr --}}
								<input type="hidden" name="_method" value="PUT">
							@endif

							<div class="form-group row">
								<label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre de la tienda:</label>
								<div class="col-md-6">
									<input id="nombre" type="text" class="form-control {{ $errors->has('nombre') ? ' is-invalid' : ''  }}" name="nombre" value="{{ $edit ? $tienda->nombre : old('nombre') }}" required autofocus="">
									@if ($errors->has('nombre'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("nombre")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">
								<label for="descripcion" class="col-md-4 col-form-label text-md-right">Descripción:</label>
								<div class="col-md-6">
									<textarea id="descripcion" type="text" class="form-control {{ $errors->has('descripcion') ? ' is-invalid' : ''  }}" name="descripcion" value="{{ $edit ? $tienda->descripcion : old('descripcion') }}" >{{ $edit ? $tienda->descripcion : old('descripcion') }}</textarea>
									@if ($errors->has('descripcion'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("descripcion")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">
								<label for="locacion" class="col-md-4 col-form-label text-md-right">Locación del tienda:</label>
								<div class="col-md-6">
									<input id="locacion" type="text" class="form-control {{ $errors->has('locacion') ? ' is-invalid' : ''  }}" name="locacion" value="{{ $edit ? $tienda->locacion : old('locacion') }}" required>
									<input type="hidden" name="lat" id="latitud" value="">
									<input type="hidden" name="long" id="longitud" value="">
									@if ($errors->has('locacion'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("locacion")}}</strong>
										</span>
									@endif
								</div>
								<input name="mapinput" id="pac-input" class="form-control" type="text" style="width: 85%;">
								<div id="map" style="height: 400px;width: 90%;margin-left: 30px;"></div>
							</div>
							<div class="form-group row">
								<label for="nombre_contacto" class="col-md-4 col-form-label text-md-right">Nombre completo del contacto:</label>
								<div class="col-md-6">
									<input id="nombre_contacto" type="text" class="form-control {{ $errors->has('nombre_contacto') ? ' is-invalid' : ''  }}" name="nombre_contacto" value="{{ $edit ? $tienda->nombre_contacto : old('nombre_contacto') }}" required>
									@if ($errors->has('nombre_contacto'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("nombre_contacto")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">
								<label for="puesto_contacto" class="col-md-4 col-form-label text-md-right">Puesto del contacto:</label>
								<div class="col-md-6">
									<input id="puesto_contacto" type="text" class="form-control {{ $errors->has('puesto_contacto') ? ' is-invalid' : ''  }}" name="puesto_contacto" value="{{ $edit ? $tienda->puesto_contacto : old('puesto_contacto') }}" required>
									@if ($errors->has('puesto_contacto'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("puesto_contacto")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">
								<label for="correo_contacto" class="col-md-4 col-form-label text-md-right">Correo electronico del contacto:</label>
								<div class="col-md-6">
									<input id="correo_contacto" type="text" class="form-control {{ $errors->has('correo_contacto') ? ' is-invalid' : ''  }}" name="correo_contacto" value="{{ $edit ? $tienda->correo_contacto : old('correo_contacto') }}" required>
									@if ($errors->has('correo_contacto'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("correo_contacto")}}</strong>
										</span>
									@endif
								</div>
								<label for="telefono_contacto" class="col-md-4 col-form-label text-md-right">Telefono celular del contacto:</label>
								<div class="col-md-6">
									<input id="telefono_contacto" type="text" class="form-control {{ $errors->has('telefono_contacto') ? ' is-invalid' : ''  }}" name="telefono_contacto" value="{{ $edit ? $tienda->telefono_contacto : old('telefono_contacto') }}" required>
									@if ($errors->has('telefono_contacto'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("telefono_contacto")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">
								<label for="telefono" class="col-md-4 col-form-label text-md-right">Telefono de la tienda:</label>
								<div class="col-md-6">
									<input id="telefono" type="text" class="form-control {{ $errors->has('telefono') ? ' is-invalid' : ''  }}" name="telefono" value="{{ $edit ? $tienda->telefono : old('telefono') }}" required>
									@if ($errors->has('telefono'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("telefono")}}</strong>
										</span>
									@endif
								</div>
							</div>
							

						<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Registrar tienda
                                </button>
                            </div>
                        </div>
						</form>

						
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection
@section('script')
	{{-- expr --}}
	<script type="text/javascript">
		function disabled(text) {
			// body...
			alert("Por favor registrar la tienda antes de agregar las "+text);
		}
	</script>
    {{-- <script> --}}
    <script>
    var map;
    function loadScript(src,callback){
        var script = document.createElement("script");
        script.type = "text/javascript";
        if(callback)script.onload=callback;
        document.getElementsByTagName("head")[0].appendChild(script);
        script.src = src;
    }
    loadScript('http://maps.googleapis.com/maps/api/js?v=3&sensor=false&callback=initialize&libraries=places&key=AIzaSyDB7vM7QxW9j-ez6hclJrkwMdAC6RzTbxc',
            function(){/*log('google-loader has been loaded, but not the maps-API ');*/});
    function initialize() 
    {
      //log('maps-API has been loaded, ready to use');
      var mapOptions = {
          zoom: 8,
          center: new google.maps.LatLng(19.390858961426655,-99.14361265000002),
          mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      map = new google.maps.Map(document.getElementById('map'),
              mapOptions);
      var marker = new google.maps.Marker({
          map: map,
          draggable:true,
          anchorPoint: new google.maps.Point(0, -29)
      });
      marker.setMap( map );
      var input = /** @type {!HTMLInputElement} */(
              document.getElementById('pac-input'));
      google.maps.event.addDomListener(input, 'keydown', function(e) {
          if (e.keyCode == 13) {
              e.preventDefault();
          }
      });
      google.maps.event.addListener(map, 'click', function(event) {
          marker.setPosition( event.latLng );
          map.panTo( event.latLng );
          var geocoder = geocoder = new google.maps.Geocoder();
          geocoder.geocode({ 'latLng': event.latLng }, function (results, status) {
              if (status == google.maps.GeocoderStatus.OK) {
                  if (results[0]) {
                      document.getElementById('latitud').value = marker.position.lat();
                      document.getElementById('longitud').value = marker.position.lng();
                      document.getElementById('locacion').value = results[0].formatted_address;
                  }
              }
          });
      });
      var types = document.getElementById('type-selector');
      map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
      map.controls[google.maps.ControlPosition.TOP_LEFT].push(types);

      var autocomplete = new google.maps.places.Autocomplete(input);
      autocomplete.bindTo('bounds', map);

      var infowindow = new google.maps.InfoWindow();

      if(navigator.geolocation) {
          browserSupportFlag = true;
          navigator.geolocation.getCurrentPosition(function(position) {
              initialLocation = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
              map.setCenter(initialLocation);
              map.setZoom(17);
          }, function() {
              map.setCenter(new google.maps.LatLng(19.390858961426655,-99.14361265000002));
              map.setZoom(17);

          });
      }
      // Browser doesn't support Geolocation
      else {
          browserSupportFlag = false;
          map.setCenter(new google.maps.LatLng(19.390858961426655,-99.14361265000002));
          map.setZoom(17);
      }

      autocomplete.addListener('place_changed', function() {
          infowindow.close();
          marker.setVisible(false);
          var place = autocomplete.getPlace();
          if (!place.geometry) {
              window.alert("Error");
              return;
          }
          // If the place has a geometry, then present it on a map.

          if (place.geometry.viewport) {
              map.fitBounds(place.geometry.viewport);
          } else {
              map.setCenter(place.geometry.location);
              map.setZoom(17);  // Why 17? Because it looks good.
          }
          marker.setIcon(/** @type {google.maps.Icon} */({
              url: place.icon,
              size: new google.maps.Size(50, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(35, 35)
          }));
          marker.setPosition(place.geometry.location);
          marker.setVisible(true);

          var address = '';
          if (place.address_components) {
              address = [
                  (place.address_components[0] && place.address_components[0].short_name || ''),
                  (place.address_components[1] && place.address_components[1].short_name || ''),
                  (place.address_components[2] && place.address_components[2].short_name || '')
              ].join(' ');
          }
          document.getElementById('locacion').value = address;
          infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
          infowindow.open(map, marker);
          document.getElementById('latitud').value = marker.position.lat();
          document.getElementById('longitud').value = marker.position.lng();
          document.getElementById('locacion').value = address;
      });
    }
	</script>
@endsection

resources/views/tiendas/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid" align="center">
	<main class="py-4" id="app">
       <div class="container">
		  	<div class="row justify-content-center">
				<div class="container-fluid card">
					<div class="container">
						<div class="col">
							<h1>Tiendas</h1>
						</div>
						<div class="col-3 input-group input-group-lg mb-3">
					  		<a href="{{ route('tiendas.create') }}" class="btn btn-primary">Agregar Nueva Tienda</a>
						</div>
					</div>
					<table class="table">
						<thead class="thead-dark">
							<tr>
								<th scope="col">Tienda</th>
								<th scope="col">Descripción</th>
								<th scope="col">Locación</th>
								<th scope="col">Contacto</th>
								<th scope="col">Telefono</th>
								<th scope="col">Acción</th>
							</tr>
						</thead>
						<tbody>
							@forelse ($tiendas as $tienda)
								{{-- expr --}}
								<tr>
									<th scope="row">{{$tienda->nombre}}</th>
									<th>{{$tienda->descripcion}}</th>
									<th>{{$tienda->locacion}} <a href="{{$tienda->getMapLink()}}" target="_blank">Ver en GoogleMaps</a></th>
									<th>{{$tienda->nombre_contacto}}</th>
									<th>{{$tienda->telefono_contacto}}</th>
									<th>
										<a href="{{ route('tiendas.productos.index',['tienda'=>$tienda]) }}" class="btn btn-link">Productos</a>
										<a href="{{ route('tiendas.edit',['tienda'=>$tienda]) }}" class="btn btn-link">Editar</a>
										<form method="POST" action="{{ route('tiendas.destroy',['tienda'=>$tienda]) }}">
											@csrf
											<input type="hidden" name="_method" value="DELETE">
											<button type="submit" class="btn btn-link" onclick="return confirm('¿Estás seguro que desea eliminar esta tienda?');">Eliminar</button>
										</form>
									</th>
								</tr>
							@empty
								{{-- empty expr --}}
								<div class="alert alert-danger" role="alert">
									<span>No hay tiendas</span>
								</div>
							@endforelse
						</tbody>
					</table>
				</div>
			</div>
		</div>
    </main>
</div>
@endsection