routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//---------------------------------------------------------
Route::get('contacto',function(){

	return View::make('contacto.index');
});
Route::get('tienda',function(){

	return View::make('tiendas.index');
});
Route::get('nosotros',function(){

	return View::make('nosotros.index');
});

Route::resource('tiendas','Web\Tienda\TiendaController');
Route::resource('tiendas.productos','Web\Tienda\TiendaProductoController');
Route::resource('tiendas.productos.fotos','Web\Tienda\TiendaProductoFotoController',['only'=>['index','destroy']]);
Route::resource('handbooks','Web\Handbook\HandbookController');

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    //
    protected $table="producto";

    protected $fillable=[
    	'id',
    	'nombre',
    	'descripcion',
    	'producto_id',
    	'producto_type',
    	'cantidad',
    	'precio'

    ];

    protected $hidden=[
    	'created_at',
    	'updated_at',
    ];

    public function producto(){
    	return $this->morphTo();
    }

    public function fotos(){
    	return $this->hasMany('App\FotoProducto', 'producto_id','id');
    }
}

app/Tienda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tienda extends Model
{
    //

    protected $table="tienda";

    protected $fillable=[
    	'id',
    	'nombre',
    	'descripcion',
    	'nombre_contacto',
    	'puesto_contacto',
    	'correo_contacto',
    	'telefono_contacto',
    	'telefono',
    	'long',
    	'lat',
    	'locacion'
    ];

    protected $hidden=[
    	'created_at',
    	'updated_at',
    ];

    public function productos(){
    	return $this->morphMany('App\Producto','producto');
    }

    public function getMapLink(){
        return 'https://www.google.com.mx/maps?q=' . $this->lat . ',' . $this->long;
    }


}

app/Http/Controllers/Api/Producto/ProductoController.php
<?php

namespace App\Http\Controllers\Api\Producto;

use App\Producto;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $productos = Producto::orderBy('nombre','asc')->get();
        foreach ($productos as $producto) {
            $producto->producto;
            $producto->fotos;
        }
        return response()->json(['productos'=>$productos],200);
    }

}

app/Http/Controllers/Web/Tienda/TiendaController.php
<?php

namespace App\Http\Controllers\Web\Tienda;

use App\Tienda;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class TiendaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $tiendas = Tienda::paginate(5);
        return view('tiendas.index',['tiendas'=>$tiendas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $edit = false;
        return view('tiendas.form',['edit'=>$edit]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
         $rules = [
            'nombre'=> 'required',
            'nombre_contacto'=>'required',
            'puesto_contacto'=>'required',
            'correo_contacto'=>'required',
            'telefono_contacto'=>'required',
            'locacion'=> 'required',
            'telefono'=> 'required'
        ];
        $this->validate($request,$rules);
        $tienda = Tienda::create($request->all());

        return redirect()->route('tiendas.productos.create',['tienda'=>$tienda]);


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function show(Tienda $tienda)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function edit(Tienda $tienda)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tienda $tienda)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tienda $tienda)
    {
        //
        foreach ($tienda->productos as $producto) {
            foreach ($producto->fotos as $foto) {
                $delete =Storage::delete('/public/'.$foto->image_path);
                if ($delete) {
                    $foto->delete();
                }
            }
            $producto->delete();
        }
        $tienda->delete();
        return redirect()->route('tiendas.index');
    }
}

app/Http/Controllers/Web/Tienda/TiendaProductoController.php
<?php

namespace App\Http\Controllers\Web\Tienda;

use App\Http\Controllers\Controller;
use App\Producto;
use App\Tienda;
use App\FotoProducto;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;

class TiendaProductoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Tienda $tienda)
    {
        //
        $productos = $tienda->productos()->get();
        return view('tiendas.producto.index',['tienda'=>$tienda,'productos'=>$productos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Tienda $tienda)
    {
        //
        $edit = false;
        return view('tiendas.producto.form',['tienda'=>$tienda,'edit'=>$edit]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Tienda $tienda,Request $request)
    {
        //
        // dd($request->all());
        // dd($imagenes);
        $inputs = $request->all();
        $rules = [
            'nombre'=>'required',
            'cantidad' => 'required|numeric',
            'precio' => 'required|numeric',
            'imagen[]'=> 'image|mimes:jpg,jpeg,png',
        ];
        $imagenes = $request->imagen;
        $this->validate($request,$rules);
        $producto = Producto::create([
            "nombre" => $inputs['nombre'],
            'descripcion' => $inputs['descripcion'],
            'producto_id' => $inputs['tienda_id'],  
            'producto_type' => "App\Tienda",
            'cantidad' => $inputs['cantidad'],
            'precio' => $inputs['precio']
        ]);
        foreach ($imagenes as $imagen) {
            $path_image = $imagen->storeAs('productos/'.$producto->id,str_random(10).'.jpg','public');
            FotoProducto::create([
                'producto_id'=>$producto->id,
                'image_path'=>$path_image,
            ]);
        }


        return redirect()->route('tiendas.productos.index',['tienda'=>$tienda]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function show(Tienda $tienda,Producto $producto)
    {
        //
        // return view('tiendas.producto.show',['producto'=>$producto,'tienda'=>$tienda]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function edit(Tienda $tienda,Producto $producto)
    {
        //
        $edit = true;
        return view('tiendas.producto.form',['tienda'=>$tienda,'producto'=>$producto, 'edit'=>$edit]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tienda $tienda,Producto $producto)
    {
        //
        $inputs = $request->all();
        $rules = [
            'nombre'=>'required',
            'cantidad' => 'required|numeric',
            'precio' => 'required|numeric',
        ];
        $this->validate($request,$rules);
        $producto->update([
            "nombre" => $inputs['nombre'],
            'descripcion' => $inputs['descripcion'],
            'cantidad' => $inputs['cantidad'],
            'precio' => $inputs['precio']
        ]);
        if ($request->imagen) {
            $imagenes = $request->imagen;
            foreach ($imagenes as $imagen) {
            $path_image = $imagen->storeAs('productos/'.$producto->id,str_random(10).'.jpg','public');
            FotoProducto::create([
                'producto_id'=>$producto->id,
                'image_path'=>$path_image,
            ]);
        }
        }
        return redirect()->route('tiendas.productos.index',['tienda'=>$tienda]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tienda  $tienda
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tienda $tienda, Producto $producto)
    {
        //
        // dd($producto);
        if($producto->producto_id == $tienda->id && $producto->producto_type == 'App\Tienda'){
            foreach ($producto->fotos as $foto) {
                $delete =Storage::delete('/public/'.$foto->image_path);
                if ($delete) {
                    $foto->delete();
                }
            }
            $producto->delete();
        }
        return redirect()->route('tiendas.productos.index',['tienda'=>$tienda]);
    }
}

app/Http/Controllers/Web/Tienda/TiendaProductoFotoController.php
<?php

namespace App\Http\Controllers\Web\Tienda;

use App\FotoProducto;
use App\Producto;
use App\Tienda;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TiendaProductoFotoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Tienda $tienda,Producto $producto)
    {
        //
        $fotos = $producto->fotos;
        return view('tiendas.producto.fotos.index',['tienda'=>$tienda,'producto'=>$producto,'fotos'=>$fotos]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\FotoProducto  $fotoProducto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tienda $tienda,Producto $producto,FotoProducto $foto)
    {
        //
        if($producto->id == $foto->producto_id){
            $delete =Storage::delete('/public/'.$foto->image_path);
            if ($delete) {
                $foto->delete();
                
            }
            
        }

        return redirect()->route('tiendas.productos.fotos.index',['tienda'=>$tienda,'producto'=>$producto]);


    }
}

resources/views/tiendas/producto/form.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">
						{{$tienda->nombre}}
					</div>
					<div class="card-body">
						<h4>Producto:</h4>
						<form method="POST" action="{{ $edit == false ? route('tiendas.productos.store',$tienda) : route('tiendas.productos.update',[$tienda,$producto]) }}" enctype="multipart/form-data">
							@csrf

							@if ($edit == true)
								{{-- expr --}}
								<input type="hidden" name="_method" value="PUT">
							@endif
							<input type="hidden" name="tienda_id" value="{{$tienda->id}}">

							<div class="form-group row">
								<label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre de la producto:</label>
								<div class="col-md-6">
									<input id="nombre" type="text" class="form-control {{ $errors->has('nombre') ? ' is-invalid' : ''  }}" name="nombre" value="{{$edit ? $producto->nombre : old('nombre') }}" required autofocus="">
									@if ($errors->has('nombre'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("nombre")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">		
								<label for="descripcion" class="col-md-4 col-form-label text-md-right">Descripción de la producto:</label>
								<div class="col-md-6">
									<textarea id="descripcion" type="text" class="form-control {{ $errors->has('descripcion') ? ' is-invalid' : ''  }}" name="descripcion" value="{{ old('descripcion') }}">{{ $edit ? $producto->descripcion : old('descripcion') }}</textarea>
									@if ($errors->has('descripcion'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("descripcion")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">		
								<label for="cantidad" class="col-md-4 col-form-label text-md-right">Cantidad del producto que tienes:</label>
								<div class="col-md-6">
									<input id="cantidad" type="number" min="1" max="100" class="form-control {{ $errors->has('cantidad') ? ' is-invalid' : ''  }}" name="cantidad" value="{{$edit ? $producto->cantidad : old('cantidad') }}" required>
									@if ($errors->has('cantidad'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("cantidad")}}</strong>
										</span>
									@endif
								</div>
							</div>
							<div class="form-group row">		
								<label for="precio" class="col-md-4 col-form-label text-md-right">Precio por producto:</label>
								<div class="col-md-6">
									<input id="precio" type="number" step="0.01" min="0" class="form-control {{ $errors->has('precio') ? ' is-invalid' : ''  }}" name="precio" value="{{ $edit ? $producto->precio : old('precio') }}" required>
									@if ($errors->has('precio'))
										{{-- expr --}}
										<span class="invalid-feedback">
											<strong>{{ $errors->first("precio")}}</strong>
										</span>
									@endif
								</div>
							</div>


							<div class="form-group row field_wrapper">
								<label for='uva' class="col-md-4 col-form-label text-md-right">Fotos del producto:</label>
								<div class="input-group col-md-6">
							        <input type="file" name="imagen[]" class="file-input" accept="image/*" @if ($edit == false)
							        	{{-- expr --}}
							        	required
							        @endif>
							        <a href="javascript:void(0);" class="add_button" title="Add field"><i class="fas fa-plus"></i></a>
							    </div>
							</div>



						<div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Registrar producto
                                </button>
                            </div>
                        </div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection
@section('script')
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>

	<script>
		$(document).ready(function(){
		    var maxField = 10; //Input fields increment limitation
		    var addButton = $('.add_button'); //Add button selector
		    var wrapper = $('.field_wrapper'); //Input field wrapper
		    var fieldHTML = '<div class="input-group offset-md-4 col-md-6"><input type="file" name="imagen[]" class="file-input" accept="image/*" required><a href="javascript:void(0);" class="remove_button" title="Add field"><i class="fas fa-minus-circle"></i></a></div>'; //New input field html 
		    var x = 1; //Initial field counter is 1
		    
		    //Once add button is clicked
		    $(addButton).click(function(){
		        //Check maximum number of input fields
		        if(x < maxField){ 
		            x++; //Increment field counter
		            $(wrapper).append(fieldHTML); //Add field html
		        }
		    });
		    
		    //Once remove button is clicked
		    $(wrapper).on('click', '.remove_button', function(e){
		        e.preventDefault();
		        $(this).parent('div').remove(); //Remove field html
		        x--; //Decrement field counter
		    });
		});
	</script>	
   
@endsection

resources/views/tiendas/producto/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid" align="center">
	<main class="py-4" id="app">
       <div class="container">
		  	<div class="row justify-content-center">
				<div class="container-fluid card">
					<div class="container">
						<div class="col">
							<h1>Productos de {{$tienda->nombre}}</h1>
						</div>
						<div class="col-3 input-group input-group-lg mb-3">
					  		<a href="{{ route('tiendas.productos.create',['tienda'=>$tienda]) }}" class="btn btn-primary">Agregar Nuevo Producto</a>
						</div>
					</div>
					<table class="table">
						<thead class="thead-dark">
							<tr>
								<th scope="col">Nombre</th>
								<th scope="col">Descripción</th>
								<th scope="col">Cantidad</th>
								<th scope="col">Precio</th>
								<th scope="col">Acción</th>
							</tr>
						</thead>
						<tbody>
							@forelse ($productos as $producto)
								{{-- expr --}}
								<tr>
									<th scope="row">{{$producto->nombre}}</th>
									<th>{{$producto->descripcion}}</th>
									<th>{{$producto->cantidad}}</th>
									<th>${{$producto->precio}}</th>
									<th>
										<a href="{{ route('tiendas.productos.edit',['tienda'=>$tienda,'producto'=>$producto]) }}" class="btn btn-link">Editar producto</a>
										<a href="{{ route('tiendas.productos.fotos.index',['tienda'=>$tienda,'producto'=>$producto]) }}" class="btn btn-link">Fotos del producto</a>

										<form method="POST" action="{{ route('tiendas.productos.destroy',['tienda'=>$tienda,'producto'=>$producto]) }}">
											@csrf
											<input type="hidden" name="_method" value="DELETE">
											<button type="submit" class="btn btn-link" onclick="return confirm('¿Estás seguro que desea eliminar este producto?');">Eliminar</button>
										</form>
									</th>
								</tr>
							@empty
								{{-- empty expr --}}
								<div class="alert alert-danger" role="alert">
									<span>No hay productos</span>
								</div>
							@endforelse
						</tbody>
					</table>
				</div>
			</div>
		</div>
    </main>
</div>
@endsection